(defun num_atoms (A L) 
  (COND ( (eq A nil) 0)
        ( (eq L nil) 0)
        ( (ATOM (CAR L)) (COND ((eq (CAR L) A) (+ 1 (num_atoms A (CDR L))) )
                               ( T (+ 0 (num_atoms A (CDR L))) )
                         ))
        ( T (+ (num_atoms A (CAR L)) (num_atoms A (CDR L)) )  )
  )
)

(trace(num_atoms))
;(num_atoms 'a '(e . a))
(num_atoms 'a '(a a a))
(num_atoms 'a '((a b) (c a) (e . a)))
